### ISSUE TITLE
Polearms visual

### ISSUE THREAD

**Issue by Zausender** [azerothcore/mod-weapon-visual#11]
Doesnt work with polearms

**Comment by Helias** [comment]
Hey, can you write more details?
How to check this "Polearm visual" problem?

**Comment by Zausender** [comment]
fixed on the author repo https://github.com/poszer/mod-weapon-visual/commit/8c1805ca1cc41c32c5ebc2c6455179ab40c18a35

**Comment by FrancescoBorzi** [comment]
The issue should stay open until it is actually fixed on master branch.

@Zausender can you please open a PR with that fix?

**Comment by ghost** [comment]
@FrancescoBorzi 
I'll create the PR later today. There's also a bug in this fix which causes fist weapons to not work anymore with this module, I'll also correct this.

**Comment by ghost** [comment]
Done: #12 (included also a few further improvements)
