### ISSUE TITLE
Should use the character ID and not the char name

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-weapon-visual#13]
The DB stores the "playerName" but it should be "character_id", it's the proper way to do so

**Comment by BarbzYHOOL** [comment]
ok seems like it's useless in code in top of that xD

**Comment by Helias** [comment]
Claim requested.

Anyway, what I did so far is:
- update www-aowow
- fix some compatible issues with AC and updated the README to improve them
- added a sql file in the setup (view README.md) to fit better AC with AoWoW
- some tests

May, can miss something but I think that the 80-90% at least, is compatible with AzertohCore
