### ISSUE TITLE
Big Mistake

### ISSUE THREAD

**Issue by yexu78** [azerothcore/mod-weapon-visual#20]
azerothcore Up to date，mod-weapon-visual ，It’s unusable

worldserver，  Close on error

**Comment by pagimu** [comment]
Same here!
But I get non error. 
Worldserver.exe closed without any message. 
Only the debuggin window from Microsoft.
![image](https://user-images.githubusercontent.com/55284322/141149016-d446c417-9d89-4110-83ce-0aede54af8b5.png)

Without that module, all works fine.

**Comment by FrancescoBorzi** [comment]
it's hard to help if you don't provide additional details, for example the error you are getting

**Comment by pagimu** [comment]
Which other details can help to find the problem? Then I will check to post here.

**Comment by Err0r1** [comment]
@FrancescoBorzi 

Crashlog: https://gist.github.com/Err0r1/757d4a361e719ce36f7156f88b24a216

**Comment by acidmanifesto** [comment]
Logs reference:
https://github.com/azerothcore/mod-weapon-visual/blob/2486fe2d28f4f0316985e61723c11102943452cb/src/Npc_VisualWeapon.cpp#L193

**Comment by acidmanifesto** [comment]
Important notes per readme
If you use an old version of this module please update the table structure using this SQL statement:

**ALTER TABLE `custom_item_enchant_visuals`
CHANGE `iguid` `item_guid` int(10) unsigned NOT NULL COMMENT 'item DB guid' FIRST,
CHANGE `display` `enchant_visual_id` int(10) unsigned NOT NULL COMMENT 'enchantID' AFTER `item_guid`,
DROP `PlayerName`,
RENAME TO `mod_weapon_visual_effect`,
COMMENT='Stores the enchant IDs for the visuals of mod-weapon-visual';**

**Comment by pagimu** [comment]
Thank you. But I had updated the table and the problem exist anyway.

Crashlog: [adbad6fb19a0+_worldserver.exe_[15-11_8-5-31].txt](https://github.com/azerothcore/mod-weapon-visual/files/7536532/adbad6fb19a0%2B_worldserver.exe_.15-11_8-5-31.txt)

**Comment by pagimu** [comment]
Good Day, nobody with an idea?I love this module and I wish to use again on my server. Can I help with other details? Thank you all for your help. ( I'm sorry, english is not my nativ language. :-) )

**Comment by EricksOliveira** [comment]
I have the same problem.

**Comment by Niceguy1337** [comment]
Same problem, instant crash.

**Comment by Shadowveil-WotLK** [comment]
same problem here!
doesn't proceed on loading c++ scripts and crashs instant

**Comment by Helias** [comment]
is this issue still valid?
