### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by fluxeru** [azerothcore/mod-weapon-visual#22]
Hello together,

when I build the AC files with the module in VS 22 some errors occurs.

15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(119,27): error C2039: "PExecute" ist kein Member von "DatabaseWorkerPool<CharacterDatabaseConnection>".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\DatabaseEnv.h(37): message : Siehe Deklaration von "DatabaseWorkerPool<CharacterDatabaseConnection>"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(204,48): error C2039: "PQuery" ist kein Member von "DatabaseWorkerPool<CharacterDatabaseConnection>".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\DatabaseEnv.h(37): message : Siehe Deklaration von "DatabaseWorkerPool<CharacterDatabaseConnection>"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(213,42): error C2039: "GetUInt32" ist kein Member von "Field".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\Field.h(98): message : Siehe Deklaration von "Field"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(214,39): error C2039: "GetUInt32" ist kein Member von "Field".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\Field.h(98): message : Siehe Deklaration von "Field"

Thanks for any possible help

**Comment by Shadowveil-WotLK** [comment]
Hey ho! =)
just implement my pr then you should be fine =)
had the same errors like u on build... updated some stuff and worked afterwards to build it =)

grüße aus wien =)
