### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Naxxramas-Server** [azerothcore/mod-weapon-visual#3]
The server crash when player switch  an enchanted off hand

**Comment by talamortis** [comment]
can you provide crash log, thanks.

**Comment by talamortis** [comment]
and can you also provide, how to reproduce?

**Comment by milestorme** [comment]
yeah mines crashing with visiual enchant module too, i didnt run in debug , the only console error i get is `segmentation faullt` and this time it happened when a player was trying to login , every time the one player would log in it would crash the server

**Comment by talamortis** [comment]
for a quick fix till i get more time to look into it you could always add at this line https://github.com/azerothcore/mod-weapon-visual/blob/master/src/Npc_VisualWeapon.cpp#L229

```
 if (!pItem)
  return;
```

this will just stop the crashing till i can get more time to check this issue

**Comment by Dreaxxx** [comment]
I think with that , server not crash , but fake enchant in the Off-Hand not saved after changing off-hand weapon or disconnection

**Comment by talamortis** [comment]
correct, but its a temp fix to stop crash just till i can look into the source itself and see why its crashing.

**Comment by milestorme** [comment]
really keen to get this crash resolved. am I  applying that to line 229 to stop the crash? is there more to do or is that enough ?

**Comment by Naxxramas-Server** [comment]
That is a temp fix , not the must , because that's stop crash the server but the offhand not rly saved and disapear after swaping weapon or disconection

**Comment by BarbzYHOOL** [comment]
Damn this is a very cool module, need to fix
