### ISSUE TITLE
Cleanup item GUIDs in the DB

### ISSUE THREAD

**Issue by ghost** [azerothcore/mod-weapon-visual#6]
As far as I see the GUIDs will pile up over time as they are never removed from the DB. Is it somehow possible to automatically cleanup GUIDs for items which don't exist anymore?

**Comment by milestorme** [comment]
Something like this `  // Delete unused rows from DB table
   CharacterDatabase.DirectExecute("DELETE FROM custom_item_enchant_visuals WHERE NOT EXISTS(SELECT 1 FROM item_instance WHERE custom_item_enchant_visuals.iguid = item_instance.guid)");
   }`

**Comment by ghost** [comment]
Thanks, I'll try to figure something out. Perhaps execute the statement during "OnStartup" (WorldScript).

**Comment by milestorme** [comment]
Yeah I was trying to think when the best time to execute it was , this is a modified version of rochet2 random visuals , I checked his script for the command to clean up he was running it on player login in the playerscript https://gist.github.com/Rochet2/8693564

**Comment by ghost** [comment]
In fact he is executing it in the constructor of the player script. This is a good idea, will create a PR for this.
