### ISSUE TITLE
Visual does not stick after logout

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/mod-weapon-visual#9]
Seems bugged?
189d4db1a7d5

**Comment by disclosurez** [comment]
Seems that this is occuring because of transmog module taking priority, can this be loaded after the transmog module somehow maybe?

**Comment by BarbzYHOOL** [comment]
so without transmog it's fine?

**Comment by ghost** [comment]
I'm using this for months together with the transmog module and have no issues.

**Comment by ghost** [comment]
@disclosurez 
Could you please apply PR https://github.com/azerothcore/mod-transmog/pull/27 for mod-transmog and test once more together with mod-weapon-visual?

**Comment by ghost** [comment]
Fixed with this commit: https://github.com/azerothcore/mod-transmog/commit/35369428ab42365de9eb301a4ef83d4376ecde73
